config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # トップページのルーティング
  root 'messages#index'
  # 一括で基本的なアクションのルーティングを設定
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[destroy edit update]
  def index
    # モデルのすべての要素を配列で取得
    @messages = Message.all
  end

  def create
    @message = Message.create!(message_params)
  end

  def destroy
    @message.destroy!
  end

  def edit
  end

  def update
    @message.update!(message_params)
  end

  def new
  end

  private
    def message_params
      params.require(:message).permit(:content)
    end

    def set_message
      @message = Message.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with model: message, local: false do |f| %>
  <%= f.text_field :content %>
  <%= f.submit value %>
  <% if value == '更新' %>
    <%= link_to '取消', new_message_path, data: { remote: true } %>
  <% end %>
<% end %>

app/views/messages/_message.html.erb
<p id="message-<%= message.id %>">
<%  # messageのcontentカラムのデータを参照 %>
  <%= message.content %>
  <%= link_to '更新', edit_message_path(message), data: { remote: true } %>
  <%= link_to '削除', message_path(message),
              method: :delete,
              data: { confirm: '削除しますか?', remote: true } %>
</p>

app/views/messages/create.js.erb
document.getElementById('messages').insertAdjacentHTML('beforeend', '<%= j(render @message) %>')
document.getElementById('message_content').value = ''

app/views/messages/destroy.js.erb
document.getElementById('message-<%= @message.id %>').outerHTML = ''

app/views/messages/edit.js.erb
var form = document.getElementsByTagName('form')[0]
form.outerHTML = '<%= j(render 'form', message: @message, value: '更新') %>'

app/views/messages/index.html.erb
<%= render 'form', message: Message.new, value: '投稿' %>
<hr>
<div id="messages">
  <%
=begin%>
 <%= render partial: 'message', collection: @messages %> を省略した書き方 
 @messagesから要素が一つずつ取り出され、部分テンプレート内の変数messageに入れられる
<%
=end%>
  <%= render @messages %>
</div>

app/views/messages/new.js.erb
var form = document.getElementsByTagName('form')[0]
form.outerHTML = '<%= j(render 'form', message: Message.new, value: '投稿') %>'

app/views/messages/update.js.erb
document.getElementById('message-<%= @message.id %>').innerHTML = '<%= j(render @message) %>'
var form = document.getElementsByTagName('form')[0]
form.outerHTML = '<%= j(render 'form', message: Message.new, value: '投稿') %>'